# Generated by Django 3.1.2 on 2020-10-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sizevariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariant',
            name='size',
            field=models.CharField(choices=[('S', 'Small.'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=5),
        ),
    ]
